MAIN_SCRIPT = "hiragana"
DEFAULT_Q_SCRIPT = "romaji"
DEFAULT_A_SCRIPT = "hiragana"

scripts = ["hiragana", "romaji"]

letters = [
    {"romaji": "a", "hiragana": "あ", "category": "a"},
    {"romaji": "i", "hiragana": "い", "category": "a"},
    {"romaji": "u", "hiragana": "う", "category": "a"},
    {"romaji": "e", "hiragana": "え", "category": "a"},
    {"romaji": "o", "hiragana": "お", "category": "a"},
    {"romaji": "ka", "hiragana": "か", "category": "ka"},
    {"romaji": "ki", "hiragana": "き", "category": "ka"},
    {"romaji": "ku", "hiragana": "く", "category": "ka"},
    {"romaji": "ke", "hiragana": "け", "category": "ka"},
    {"romaji": "ko", "hiragana": "こ", "category": "ka"},
    {"romaji": "sa", "hiragana": "さ", "category": "sa"},
    {"romaji": "shi", "hiragana": "し", "category": "sa"},
    {"romaji": "su", "hiragana": "す", "category": "sa"},
    {"romaji": "se", "hiragana": "せ", "category": "sa"},
    {"romaji": "so", "hiragana": "そ", "category": "sa"},
    {"romaji": "ta", "hiragana": "た", "category": "ta"},
    {"romaji": "chi", "hiragana": "ち", "category": "ta"},
    {"romaji": "tsu", "hiragana": "つ", "category": "ta"},
    {"romaji": "te", "hiragana": "て", "category": "ta"},
    {"romaji": "to", "hiragana": "と", "category": "ta"},
    {"romaji": "na", "hiragana": "な", "category": "na"},
    {"romaji": "ni", "hiragana": "に", "category": "na"},
    {"romaji": "nu", "hiragana": "ぬ", "category": "na"},
    {"romaji": "ne", "hiragana": "ね", "category": "na"},
    {"romaji": "no", "hiragana": "の", "category": "na"},
    {"romaji": "ha", "hiragana": "は", "category": "ha"},
    {"romaji": "hi", "hiragana": "ひ", "category": "ha"},
    {"romaji": "fu", "hiragana": "ふ", "category": "ha"},
    {"romaji": "he", "hiragana": "へ", "category": "ha"},
    {"romaji": "ho", "hiragana": "ほ", "category": "ha"},
    {"romaji": "ma", "hiragana": "ま", "category": "ma"},
    {"romaji": "mi", "hiragana": "み", "category": "ma"},
    {"romaji": "mu", "hiragana": "む", "category": "ma"},
    {"romaji": "me", "hiragana": "め", "category": "ma"},
    {"romaji": "mo", "hiragana": "も", "category": "ma"},
    {"romaji": "ya", "hiragana": "や", "category": "ya"},
    {"romaji": "yu", "hiragana": "ゆ", "category": "ya"},
    {"romaji": "yo", "hiragana": "よ", "category": "ya"},
    {"romaji": "ra", "hiragana": "ら", "category": "ra"},
    {"romaji": "ri", "hiragana": "り", "category": "ra"},
    {"romaji": "ru", "hiragana": "る", "category": "ra"},
    {"romaji": "re", "hiragana": "れ", "category": "ra"},
    {"romaji": "ro", "hiragana": "ろ", "category": "ra"},
    {"romaji": "wa", "hiragana": "わ", "category": "wa"},
    {"romaji": "wo", "hiragana": "を", "category": "wa"},
    {"romaji": "n", "hiragana": "ん", "category": "n"},
]
